#NOTE: If non-alphanumeric characters are present, enclose in value in quotes.

[dev]
    scheme = sftp
    user = master-66609868
    pass = ZEUqXYYDK94jfK2
    #privkey = 'F:/Developers/Project/Fyxify/Dev/Key/fyxify-dev.pem'
    host = 139.162.8.54
    path = /applications/customer-dev.tayaree.com/public_html/

    ; 1. Local path to the folder you want to sync
    base = "customer-web"

    port = 2722
    #File permission set on the uploaded files/directories
    permissions = 0777
    #File permissions set on newly created directories
    directoryPerm = 0777
    #Files that should be ignored and not uploaded to your server, but still tracked in your repository
    exclude[] = 'backend/*.ini'
    exclude[] = 'backend/_ide_helper.php'
    exclude[] = ".git/"
    exclude[] = "frontend/"
    exclude[] = "customer-web/node_modules/"
    exclude[] = ".env"
    exclude[] = ".idea/"
    exclude[] = ".vscode/"
